# Generated by Django 4.2 on 2026-01-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='readTime',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
