# Generated by Django 4.2 on 2026-01-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_readtime_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='readTime',
            field=models.CharField(default=0, help_text='Estimated read time in minutes', max_length=100),
        ),
    ]
