# Generated by Django 4.2 on 2026-02-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_readtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authorTitle',
            field=models.CharField(default='Full-Stack Developer', help_text='Your Profesion', max_length=100),
        ),
    ]
